### ISSUE TITLE
[Checklist de Soft Skills e Carreira]

### ISSUE THREAD

**Issue by KaueASB** [KaueASB/trybe-exercicios#12]
## Parte 1 - Criando um portfólio (Currículo, GitHub e LinkedIn)
- [ ] O meu currículo está de acordo com as [diretrizes que estudamos](https://app.betrybe.com/course/career/personal_portfolio/como-criar-um-curriculo-incrivel/eb727934-471c-4f72-b647-0dc06eef5ae2/modelo-de-curriculo-aprenda-a-fazer-o-seu/253bb3a1-b6d1-4cf2-99c1-15465cbe667b/qual-a-importancia-de-um-bom-curriculo/97e86e3f-c473-43a1-aea8-61ea7fc917ff).
- [ ] Tenho um [Linkedin Campeão.](https://app.betrybe.com/course/career/personal_portfolio/linkedin-campeao/0739294e-dcc7-4809-8f84-45708f7d3c27/melhores-praticas-de-linkedin/78667cd4-def8-4f19-a45a-c61416375b37?use_case=side_bar)
- [x] Meu [GitHub](https://app.betrybe.com/course/career/personal_portfolio/github-perfil-e-readmes/ea1e5823-b988-4c8b-9034-84f522b4108f/o-que-e/373959a1-060e-42af-af58-ee4f4512dc90?use_case=side_bar) tem README de perfil, GitHub Stats, Stacks e tecnologias que conheço.
- [x] Meu GitHub tem [projetos pinados](https://app.betrybe.com/course/career/personal_portfolio/github-publicando-projetos-feitos-na-trybe/d7ca7f50-0a8f-4b10-b360-cfcb454d832a/porque-isso-e-importante/7f80f487-4380-4d0c-b357-63e36efd7374?use_case=side_bar) e com README.

## Parte 2 - Entendendo minha história 
- [ ] Fiz a [atividade sobre minha história de vida.](https://app.betrybe.com/course/soft-skills/inteligencia-emocional/historia-de-vida/c252d61e-0df5-4012-ba29-de4e5d4542e0/historia-de-vida/1751f2bc-9a46-4c4a-87ff-8fac1a8c0c04)
- [x] Entendo quais são os [valores](https://app.betrybe.com/course/soft-skills/inteligencia-emocional/valores/d184ebe4-9a1b-4b91-a008-1a63555a1d97/identificando-nossos-valores-pessoais/2b6cab51-f584-433f-ad27-61183c5343cd?use_case=side_bar) que eu admiro
- [ ] Sei quais são meus principais [talentos](https://app.betrybe.com/course/soft-skills/inteligencia-emocional/talentos/5fb237ef-f85b-46ee-a5c9-4b4f0ba85aa7/talentos/a922a7ae-bbbe-41b5-b0ec-1de3c7e3cc7d?use_case=side_bar) e pontos fortes
- [ ] Sei quais são meus principais [pontos de melhoria](https://app.betrybe.com/course/soft-skills/criatividade/curriculo-de-falhas/e656acf7-21b4-48dd-ae4b-89e777648493/objetivos-de-aprendizagem/782d2602-216d-496b-a2e4-bc5ced04d98e)

## Parte 3 - Estabelecendo objetivos
- [x] Sei dos meus objetivos a **curto** prazo.
- [x] Sei dos meus principais objetivos a **médio** prazo.
- [ ] Sei dos meus principais objetivos a **longo** prazo.
- [ ] Consigo [projetar meu futuro](https://app.betrybe.com/course/soft-skills/inteligencia-emocional/projetando-o-futuro/810a3f6d-b574-4e4b-a9b0-cc197432281a/projetando-o-futuro/ad761b87-ddd2-45ed-bf31-be89c7f1848f?use_case=side_bar) e definir metas para atingir meus objetivos.
- [ ] Tenho um [plano de desenvolvimento pessoal](https://app.betrybe.com/course/soft-skills/lideranca/criacao-de-pdi/44bf2885-31ec-4bfb-b772-b690b11dadb6/para-onde-direcionar-a-propria-vida/fdfa8b42-40f6-4aa7-af78-948ab581252a) (PDI)

## Parte 4 - Praticando para processos seletivos
- [ ] Pratiquei o storytelling a partir de roteiros de pitch de 1, 2 e 5 minutos.
      - [Conteúdo "Storytelling & Carreira". ](https://app.betrybe.com/course/soft-skills/pensamento-critico/pensamento-critico-storytelling-de-carreira-em-tecnologia/0dbcb574-df3b-4c43-a501-bc800c0719a6/o-que-e-storytelling-e-o-que-isto-tem-a-ver-com-a-nossa-carreira/d7b82765-89cf-4ba5-990a-b4ac06f923f5?use_case=side_bar)
      - [Conteúdo "Storytelling para entrevistas".](https://app.betrybe.com/course/career/first_interview/storytelling-e-como-utiliza-lo-em-entrevistas/cbbccf27-4419-419c-9d9e-eb7862c1f4d1/o-que-e-storytelling-e-por-que-ele-importa/80218cdd-70b7-4b23-bd40-70bdaef891ea)
- [x] Participei da mentoria de pitch (segunda mentoria de Soft Skills) ou compartilhei ele com o time de soft skills para receber feedbacks.
- [ ] Implementei melhorias no meu pitch com base nos feedbacks recebidos
- [ ] Fiz meu treino de pitch novamente (27/07 com time de carreira).
- [ ] Participei do treino de perguntas mais comuns em entrevistas (27/07 com time de carreira).
